name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build (Optional)
      run: echo "Build step - if needed"

    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 13.49.78.93
        username: ec2-user
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "."
        target: "/home/ec2-user/simple-nodejs-app"
