name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-nodejs-app:v1 .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-nodejs-app:v1

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/simple-nodejs-app:v1
            docker stop node-app || true
            docker rm node-app || true
            docker run -d -p 5005:5000 --name node-app ${{ secrets.DOCKER_USERNAME }}/simple-nodejs-app:v1
